# Generated by Django 3.2.7 on 2021-09-23 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='UserProfile',
            new_name='user_profile',
        ),
    ]
